### ISSUE TITLE
Implement TikaFeature

### ISSUE THREAD

**Issue by yclim** [yclim/gem#59]
extract all  metadata, and tika'ed content

**Comment by orhlulu** [comment]
for tika extraction, should be quite transparent to the type of files,  all csv,excel,pdf features will use tika feature extraction for metadata, then for content extraction will go thru their individual parser for extraction

**Comment by yclim** [comment]
I think instead of spreading what tika can do to all xxx feature, centralised it into one Tikafeature is easier to implement at the UI side and easier to maintain (all tika related feature in one place)

Tika feature is also a “catch all”  that work for files that we don’t support Yet.

Can tika extract content and metadata automatically without specifying the file type?

**Comment by orhlulu** [comment]
tika currently can "magic" detect the filetype and use its own parser for metadata.. but contents better to use its own parser like poi because tika do not support sheet that well..

so tika can centralise to extract metadata.. but content better to use self own parser for better control... in this case it will become each GEMFile will have 2 feature. 1 feature for tika to extract metadata, 1 feature is for their own. either csvfeature, excelfeature or pdffeature.

for those not supported type, think yes can use tika for pure text extraction only ba.. without going too deep of what they contains.. either wav or picture or some encapsulated html

**Comment by orhlulu** [comment]
And can further streamline the codes further by letting tika decide which parser to use for metdata extraction..

**Comment by yclim** [comment]
Yeap. tikafeature will extract all metadata and pure text extraction on all file types. We can ignore files that can’t perform text extraction

**Comment by orhlulu** [comment]
ok created a pull request for tika for metadata and a general parser for all filetypes
